let generatedDocument = "";


function generateDocument() {

    const type = document.getElementById("documentType").value;

    const name = document.getElementById("name").value.trim();

    const address = document.getElementById("address").value.trim();

    const details = document.getElementById("details").value.trim();

    const output = document.getElementById("documentOutput");


    // Validation

    if (type === "") {
        alert("Please select a document type.");
        return;
    }

    if (name === "") {
        alert("Please enter your name.");
        return;
    }

    if (address === "") {
        alert("Please enter your address.");
        return;
    }


    let title = "";

    switch (type) {

        case "rental":
            title = "RENTAL AGREEMENT";
            break;

        case "affidavit":
            title = "AFFIDAVIT";
            break;

        case "notice":
            title = "LEGAL NOTICE";
            break;

        case "employment":
            title = "EMPLOYMENT AGREEMENT";
            break;

        case "nda":
            title = "NON-DISCLOSURE AGREEMENT";
            break;
    }


    generatedDocument = `
${title}

Name: ${name}

Address:
${address}

Additional Details:
${details || "No additional details provided."}


This document is generated by LegalEase
for informational and drafting purposes.

Date: ${new Date().toLocaleDateString()}
`;


    // Display document

    output.innerHTML = `
        <div class="generated-content">

            <h2 class="document-title">
                ${title}
            </h2>

            <p><strong>Name:</strong> ${name}</p>

            <p>
                <strong>Address:</strong><br>
                ${address}
            </p>

            <p>
                <strong>Additional Details:</strong><br>
                ${details || "No additional details provided."}
            </p>

            <hr>

            <p>
                This document is generated by LegalEase
                for informational and drafting purposes.
            </p>

            <p>
                <strong>Date:</strong>
                ${new Date().toLocaleDateString()}
            </p>

        </div>
    `;


    // Show buttons

    document.getElementById("downloadBtn").style.display = "block";

    document.getElementById("printBtn").style.display = "block";
}


/* Download */

function downloadDocument() {

    if (generatedDocument === "") {
        alert("Please generate a document first.");
        return;
    }


    const blob = new Blob(
        [generatedDocument],
        { type: "text/plain" }
    );


    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download = "LegalEase_Document.txt";

    link.click();

    URL.revokeObjectURL(url);
}


/* Print */

function printDocument() {

    if (generatedDocument === "") {
        alert("Please generate a document first.");
        return;
    }


    const printWindow = window.open("", "_blank");


    printWindow.document.write(`
        <html>

        <head>
            <title>LegalEase Document</title>

            <style>

                body {
                    font-family: Arial;
                    padding: 40px;
                    line-height: 1.6;
                }

                h1 {
                    text-align: center;
                }

            </style>

        </head>

        <body>

            <pre style="white-space: pre-wrap;">
${generatedDocument}
            </pre>

        </body>

        </html>
    `);


    printWindow.document.close();

    printWindow.print();
}